### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by joshday**
I was getting some errors after a fresh Pkg update.  Did some exports change in HTTP?

### CODE REVIEW

**Comment by joshday** [comment]
Sorry, I didn't test this well enough locally.  I'll give it a go tomorrow and try to get tests passing.

**Comment by haydenfree** [comment]
@joshday Hi Josh, has there been any progress on this issue? Sorry to bother/rush you, but this is causing some issues on a build server for me. Thank you! 👍

**Comment by joshday** [comment]
I thought the only issue was a change in exports/names, but it's more than that and is currently beyond me on how to fix it.  @piever mentioned on slack yesterday that he would try to look at it today.

A temporary workaround is to pin HTTP.jl to 0.7.1

**Comment by piever** [comment]
I've just opened #86, but still have some WebSockets renaming to figure out.

**Comment by haydenfree** [comment]
@joshday The issue I'm having is when Travis attempts to build documentation, is there a way to pin the version for Travis? As far as I can tell pinning only works locally.

Also thank you for the quick reply/update, I really appreciate it!

**Comment by joshday** [comment]
Are you using Documenter.jl?  From your `docs/` folder you can update your Manifest.toml file via something like:

```
]  # Pkg REPL mode
activate .
pin HTTP@0.7.1
```

Once things are fixed you'll then want to `free HTTP`

**Comment by piever** [comment]
Superseded by #86

**Pull request closed without merging**
