### PR TITLE
Add a WebSocket example for #90.

### PR DESCRIPTION
**Pull request by Losses**

### CODE REVIEW

**Comment by hustf** [comment]
I have to say I looked at the code and was impressed, just waiting for a chance to test and play with it before commenting.

**Comment by jpsamaroo** [comment]
Confirmed that this is working by using the following WS client:

```
using Mux
import Mux.WebSockets

WebSockets.open("ws://127.0.0.1:2333/ws_io") do ws_client
    WebSockets.writeguarded(ws_client, "Testing 1 2 3...")
    data, success = WebSockets.readguarded(ws_client)
    if success
        println(stderr, ws_client, " received:", String(data))
    end
end
```

@Losses would you mind adding something like the above so that we have a complete, working example in the README?

**Comment by Losses** [comment]
@jpsamaroo Okay, I'll do it this weekend.

**Comment by jpsamaroo** [comment]
@Losses are you still planning on adding the WebSocket client code to this PR, or would you rather I merge this as-is and add the client code later? Your call, I'm happy either way :slightly_smiling_face:

**Comment by Losses** [comment]
@jpsamaroo I don't have enough time recently because i'm looking for a job. please merge these code, i'll write a full tutorial while i have some free time.

sorry for that

**Comment by jpsamaroo** [comment]
Thanks!

**Pull request merged**
