### PR TITLE
changes the @d macro into the d function call

### PR DESCRIPTION
**Pull request by dls**
Per the discussion over here: https://github.com/JuliaWeb/Mux.jl/issues/16#issuecomment-152715691

I added a test, verified it failed, then verified the change fixed it. I'd feel more comfortable if there were more tests generally though... use at your own risk ;p

### CODE REVIEW

**Comment by one-more-minute** [comment]
Looks good, thanks!

**Comment by one-more-minute** [comment]
Tests are certainly a good idea and a great way to contribute – if you're interested in putting some together they'd be a very welcome addition.

**Comment by IainNZ** [comment]
This broke Mux on 0.3. Any reason not to switch to `julia 0.4` min version now?

**Comment by IainNZ** [comment]
(see https://travis-ci.org/JuliaWeb/Mux.jl/builds/91248587)

**Pull request merged**
