### PR TITLE
Import duty

### PR DESCRIPTION
**Pull request by cmcaine**
Looks like imports, `using`s and `export` are used to document what's used or exported from each file of the project. This PR makes some very minor changes, removing a couple that don't make sense; moving `using HTTP.URIs:URI` a few lines up to before its first use; and adding `using Lazy` in src/routing.jl so that it is slightly more discoverable that `d()` is imported from there.

I think these changes make the code a little more approachable and I hope you agree!

### CODE REVIEW

**Comment by cmcaine** [comment]
Another possibility here is to remove the dependency on Lazy.jl. As far as I can see, these are the only two parts of it that are used:

```jl
macro errs(ex)
  :(try $(esc(ex))
    catch e
      showerror(stderr, e, catch_backtrace())
      println(stderr)
    end)
end
d(xs...) = Dict{Any, Any}(xs...)
```

Removing the dependency would mean getting rid of some type piracy that Lazy.jl introduces, too (e.g. on the `split` function), which sounds like a good idea? OTOH, this is/was MikeInnes package, and they might not want Lazy.jl removed.

**Comment by jpsamaroo** [comment]
Go ahead and remove the dep on Lazy; we shouldn't depend on a package which commits type piracy, even if minimal. Also, if you want to rename `d()` to something more explanatory, that would be great :slightly_smiling_face:

**Comment by cmcaine** [comment]
I've removed Lazy.jl. I've not renamed `d()` because I quite like the name and can't think of anything better rn, so I think this is good to merge.

**Comment by cmcaine** [comment]
Bump. I think this is good to merge :)

**Comment by jpsamaroo** [comment]
Thanks!

**Pull request merged**
