### PR TITLE
Support returning an HTTP.Response

### PR DESCRIPTION
**Pull request by cmcaine**
I don't know if this is desirable or not because historically Mux has kept HTTP.jl as an implementation detail that users don't need to use or know about.

In this change, users still don't need to know about HTTP.jl, but if they want they can return HTTP.Response objects instead of a string or a dictionary.

### CODE REVIEW

**Review by jpsamaroo — APPROVED** [review]

**Comment by jpsamaroo** [comment]
Regardless of whether it crosses abstraction boundaries, this change is so simple that it doesn't really matter.

**Comment by cmcaine** [comment]
Looking at this some more, we have three methods that all do something pretty similar:

```
# src/basics.jl

Response(d::AbstractDict) =
    HTTP.Response(get(d, :status, 200),
            get(d, :headers, HTTP.Headers());
            body = get(d, :body, ""))
Response(r::HTTP.Response) = r
Response(o) = HTTP.Response(stringmime(MIME"text/html"(), o))

response(d) = d
response(s::AbstractString) = d(:body=>s)


# src/server.jl

# conversion functions for known http_handler return objects
mk_response(d) = d
function mk_response(d::Dict)
  r = HTTP.Response(get(d, :status, 200))
  haskey(d, :body) && (r.body = d[:body])
  haskey(d, :headers) && (r.headers = d[:headers])
  return r
end
```

I think we probably only need one of these. I propose removing `response` and `mk_response` and maybe renaming `Response` to `response`.

**Comment by cmcaine** [comment]
Ah, my bad, we have to keep `response` and one of `mk_response` and `Response`.

**Comment by cmcaine** [comment]
Thinking about this a bit more, I think this is a bad idea. It breaks functions like `status(404)` that expect the response to be a dict.

I'm going to close this and make a new PR that removes `mk_response` and adds docstrings.

**Pull request closed without merging**
