### PR TITLE
Port MIME type detection over from HttpServer.jl

### PR DESCRIPTION
**Pull request by rdeits**
Fixes https://github.com/JuliaGizmos/WebIO.jl/issues/181

This was broken in the transition from HttpServer.jl to HTTP.jl. There's a TODO in the code to switch to `HTTP.sniff()` but that doesn't quite work. The problem is that `HTTP.sniff()` only operates on the file contents and not the extension, so it always returns `text/plain` for things like `.css` files, while old implementation correctly returned `text/css`. 

To avoid a new dependency, I just copied over the whole `mimetypes.jl` file from HttpServer into Mux. It's not an elegant solution, but given that the current behavior is broken, I think it's necessary. In the future, we could consider moving the mimetype list elsewhere.

### CODE REVIEW

**Comment by rdeits** [comment]
Here's the old implementation that I'm essentially restoring: https://github.com/JuliaWeb/Mux.jl/blob/6aec3444d4c4b92a4de3a54ac5381c7dda596087/src/examples/files.jl#L20

**Comment by piever** [comment]
Maybe this could be moved to HTTP eventually, but for now this PR is a good practical solution.

**Comment by hustf** [comment]
Thank you for the great work you are putting in. This may belong in a new HttpCommon in the end, but for now I will refer Mux.jl in private repositories.

Would you consider including some additional extensions? I always add these lines to HttpServer (sorry for layout)

# Add some mime types, which some browsers support.
HttpServer.mimetypes["jl"]= "text/plain"
HttpServer.mimetypes["md"] = "text/markdown; charset=UTF-8"
HttpServer.mimetypes["vec"] =  "text/plain"

**Comment by rdeits** [comment]
I don't actually know much about the details of MIME types. The `.jl` one seems fine, but why is the `charset` specified only for `markdown`? And what is a `.vec` file? There seem to be a bunch of formats using that extension, some of which are binary.

**Comment by piever** [comment]
> Maybe we can decide whether to add those as part of a separate PR? I'd like to get the original issue fixed as soon as possible.

Yes! Not loading any css library right in WebIO is pretty bad, I think we can discuss in a separate PR which other mimetype detection we want to add and whether we want to allow a mechanism to customize this detection on the user side.

**Pull request merged**
