### PR TITLE
turn websockets integration back on

### PR DESCRIPTION
**Pull request by rdeits**
This is necessary to get WebIO.jl working again on 0.7

### CODE REVIEW

**Comment by simonbyrne** [comment]
Websockets.jl has now been updated. Maybe try closing and reopening?

**Comment by rdeits** [comment]
Blocked by https://github.com/vtjnash/Pidfile.jl/pull/2

**Comment by rdeits** [comment]
But I think if this works on v0.7 we should merge it. It requires Julia 0.7, so nothing will break for 0.6 users, and the situation with Pidfile.jl on 1.0 will resolve itself soon. This seems like a strict improvement and will un-block various downstream projects.

**Comment by tkoolen** [comment]
Pidfile tag PR is open: https://github.com/JuliaLang/METADATA.jl/pull/16851.

**Comment by tkoolen** [comment]
Pidfile tag merged.

**Comment by tkoolen** [comment]
🎉 !

**Comment by piever** [comment]
Amazing job! Could we simply merge this one, https://github.com/JuliaGizmos/WebIO.jl/pull/169 and https://github.com/JunoLab/Blink.jl/pull/139 ? I think it's difficult otherwise for package developers to test things on travis. I agree with @rdeits that this is a strict improvement anyway as before WebSockets integration was simply not working.

**Comment by rdeits** [comment]
This is now passing all the tests, so I'd say we should merge it, tag a new release, and then move on to the WebIO and Blink PRs.

**Comment by tkoolen** [comment]
Ready to go?

**Comment by MikeInnes** [comment]
Thanks!

**Comment by rdeits** [comment]
Can we also get a new tag with this PR included? That will get WebIO and Blink closer to working.

**Comment by MikeInnes** [comment]
I added you as a committer so you can do what you need to.

**Pull request merged**
