### PR TITLE
Rename "probabilty" -> "probability"

### PR DESCRIPTION
**Pull request by cmcaine**
It's a typo. I don't know if this is worth doing or not, though!

### CODE REVIEW

**Review by jpsamaroo — APPROVED** [review]
LGTM! Could you also bump the patch version so that downstream users can migrate to the properly-named variant without the depwarn?

**Comment by cmcaine** [comment]
Thanks! Sorry, I don't really know how `@deprecate` works. Would you like me to:

1. bump the version to 0.7.4 and remove `@deprecate`?
2. put out commits bumping versions where 0.7.4 will be released with `@deprecate` and 0.7.5 will be released without?
3. do something else?

**Comment by jpsamaroo** [comment]
Just bump the version to 0.7.4; downstream packages can then fix usage of the typo version on their end and lower-bound Mux to 0.7.4 so that earlier versions (with the typo) aren't used. If packages don't lower-bound, they just get the (approximately harmless) depwarn. We can remove the depwarn when Mux eventually goes to 1.0, or maintaining the typo definition becomes cumbersome.

**Comment by cmcaine** [comment]
Done now, ready to merge.

**Comment by jpsamaroo** [comment]
Thanks!

**Pull request merged**
